import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-2xl underline bg-front text-white">Netflix</div>

    </div>
  )
}
