import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Home from '../components/home/Home'

export default function App() {
  const {data:session} = useSession()
  const router = useRouter()
  useEffect(()=> {
    if(session)router.push('/netflix')
    else router.push('/')
  },[])
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* landing page */}
      <Home/>
    </div>
  )
}
